### ISSUE TITLE
Use 'submit' event to submit form

### ISSUE THREAD

**Issue by joostf** [SadisticSun/web-app-from-scratch#14]
https://github.com/SadisticSun/web-app-from-scratch/blob/123a41b8dc8091cbf41f64f6e3eb350e7f49ace5/opzet%20spa/static/js/app.js#L43

**Comment by TristanJacobs89** [comment]
can't get this to work.. submit eventlistener doesn't seem to fire the included callback function even when preventDefault() has been added.
