### ISSUE TITLE
Use a predefined selectvalue. 

### ISSUE THREAD

**Issue by sahanay** [SadisticSun/web-app-from-scratch#22]
If user doesn't select either the sticker or gif radio button, the server responds with a 404 error that is not handled by the app. Instead the spinner keeps on spinning.

`
XMLHttpRequest cannot load https://api.giphy.com/v1/undefined/search?q=cats&api_key=dc6zaTOxFJmzC&limit=25. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access. The response had HTTP status code 404.
`

Solution:  either preselect either 'gif' or 'sticker' radio button to prevent this error or refactor your formElements.selectedFilter() function that can handle the exception when none of the radiobuttons is selected.

**Comment by sahanay** [comment]
I see that this issue is solved in your V2 version.

**Comment by TristanJacobs89** [comment]
Has been fixed already by setting the attribute 'checked' on the 'gifs' radio button to be selected as default
