### ISSUE TITLE
Better handling of server output

### ISSUE THREAD

**Issue by sahanay** [SadisticSun/web-app-from-scratch#29]
When you search for "dog eat", the server responds a second gif object where somehow the image object is undefined and thus preventing the rest of the gifs to load.

![schermafbeelding 2017-05-17 om 16 06 18](https://cloud.githubusercontent.com/assets/9800812/26157951/cc4a6d42-3b1a-11e7-969d-987e06f67e17.png)

I've updated the code like this:
```JS
// this
var img_link  = item.image.url;
var item_id   = item.id;

// to
var img_link  = item.image ? item.image.url : "";
var item_id   = item.id;
```

You can see now in the console that indeed the second gif object has an undefined image property instead of an object. But the rest is loaded like it should.
![schermafbeelding 2017-05-17 om 16 10 31](https://cloud.githubusercontent.com/assets/9800812/26158204/673c7a7a-3b1b-11e7-8f4d-73e2c63b1161.png)

**Comment by TristanJacobs89** [comment]
That's a way, but a bit hacky. Ideally the 2 strings are joined together with the %20 code.

**Comment by sahanay** [comment]
The problem is not the query. The problem is the response from the server. The app has no way of handling null/undefined values which makes it crash.
